DISABLE:
  - COPYPASTE # too many false-positives
  - CSS
  - JAVASCRIPT
  - TYPESCRIPT

DISABLE_LINTERS:
  - PYTHON_BANDIT
  - REPOSITORY_SEMGREP
  - REPOSITORY_TRIVY
  - RUST_CLIPPY
  - SPELL_CSPELL

# Override default config files
DOCKERFILE_HADOLINT_CONFIG_FILE: .config/.hadolint.yaml
PYTHON_BLACK_CONFIG_FILE: .config/pyproject.toml
PYTHON_FLAKE8_CONFIG_FILE: .config/setup.cfg
PYTHON_ISORT_CONFIG_FILE: .config/pyproject.toml
PYTHON_PYLINT_CONFIG_FILE: .config/pyproject.toml
RUBY_RUBOCOP_CONFIG_FILE: .config/.rubocop.yml
YAML_YAMLLINT_CONFIG_FILE: .config/.yamllint.yml

# Config
JSON_V8R_FILTER_REGEX_EXCLUDE: composer.json
