version: 2.1

workflows:
  version: 2
  circleci:
    jobs:
      - azlint
      - install:
          matrix:
            parameters:
              image:
                - debian:11.7
                - ubuntu:20.04
                - ubuntu:22.04

jobs:
  azlint:
    docker:
      - image: matejkosiarcik/azlint:0.6.4
    steps:
      - checkout
      - run: |
          # TODO: Reenable linters
          export VALIDATE_PRETTIER=false
          if [ "$CIRCLE_BRANCH" = main ]; then
            azlint
          else
            azlint --only-changed
          fi

  install:
    parameters:
      image:
        type: string
    docker:
      - image: "<< parameters.image >>"
    steps:
      - checkout
      - run: apt-get update && apt-get install --yes python3 python3-pip python3-venv
      - run: make bootstrap
      - run: sh install.sh
