version: 2.1

workflows:
  version: 2
  circleci-build:
    jobs:
      - azlint
      - build

jobs:
  azlint:
    docker:
      - image: matejkosiarcik/azlint:0.4.5
    steps:
      - checkout
      - run: |
          if [ "$CIRCLE_BRANCH" = main ]; then
            azlint
          else
            azlint --only-changed
          fi

  build:
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - run: apt-get update && apt-get install --yes python3 python3-pip python3-venv
      - run: make bootstrap
      - run: make install
